# Machine Learning Algorithms implemented in Julia

Based on *Machine Learning* by Zhou ZhiHua

## Linear Model 

The main goal of Linear Model is to come up with a function that can make prediction based on given attributes, its basic form is like $f(x) = w_1x_1 + w_2x_2 + \cdots + w_dx_d + b$ and we can also write it in vector form $f(x) = \bf{w^{\mathtt{T}}x +b}$ where ${\bf{w}} = (w_1;w_2;w_3;...;w_d)$.<br>  When we finally learned ${\bf{w}}$ and $b$, we have also learned the Linear Model.

### Linear Regression

Linear Model is simple and easy to interprete. <br>
So we begin by Linear Regression Model which is the most basic and widedly used linear model

Given Dataset $D = \{({\bf{x_1}},y_1),({\bf{x_2}},y_2),...,({\bf{x_m}},y_m)\}$ where ${\bf{x_i}}=(x_{i1};x_{i2};...;x_{id})$ and $y_i \in \mathbb{R}$ <br>
Linear Regression Model set  ${\bf{w}}$ and $b$ which minimize the difference between $f({\bf{w}},b)$ and $y$


As for multivariate linear regression, let $X$ represents the Dataset with each row represents a single data sample and first $d$ elements stand for $d$ attributes and one be the end of every row.<br>


In [1]:
# dataset 
density = [0.697;0.774;0.634;0.608;0.556;0.403;0.481;0.437;0.666;0.243;0.245;0.343;0.639;0.657;0.360;0.593;0.719];
sugarcontent = [0.460;0.376;0.264;0.318;0.215;0.237;0.149;0.211;0.091;0.267;0.057;0.099;0.161;0.198;0.370;0.042;0.103];
label = [1;1;1;1;1;1;1;1;0;0;0;0;0;0;0;0;0];

In [2]:
# linear model result class
struct LinearModelResult
    wvec # vector of weights
    b    # additional intercepts
    predictfunc # linear predict function
    residuals # sample residuals
end

In [40]:
# Linear Regression Function
function LinearRegression(X,y)
    X = [X ones(size(X,1),1)]
    paras = inv(X' * X) * (X'* y)
    function predfunc(x)
        x * paras[1:end-1] .+ paras[end]
    end
    res = LinearModelResult(paras[1:end-1],paras[end],predfunc)
end

LinearRegression (generic function with 1 method)

In [41]:
# Linear Regression Test by given dataset
X = [density sugarcontent];
y = label;
test = LinearRegression(X,y);

In [42]:
test.predictfunc([density[1] sugarcontent[1]])

1-element Array{Float64,1}:
 1.0793855397904826

In [43]:
test.predictfunc([density sugarcontent])

17-element Array{Float64,1}:
 1.0793855397904826  
 0.9298292670457147  
 0.625691885013115   
 0.7319772303975127  
 0.485402888652371   
 0.4672447597811231  
 0.3094158914290266  
 0.4253412180254721  
 0.26304689921306795 
 0.4634739439987171  
 0.007368105543229225
 0.1410563147503745  
 0.40371735390226926 
 0.4919992990557531  
 0.7381007013794593  
 0.12491578097813938 
 0.31203292104418656 

### Logistic Regression

Logistic regression is one of the most frequently used binary classification method

In [88]:
function LogisticRegression(X,y)
    X = [X ones(size(X)[1],1)]
    β = ones(size(X)[2],1)
    Loss = sum(-y.* (X * β) + log.(1 .+ exp.(X * β)))
    dLoss = Loss
    maxtol = 1e-4
    p1(x,beta) = exp.(beta' * x) / (1 .+ exp.(beta' * x))
    while dLoss > maxtol
        partialsq = sum(map(i -> X[i,:] * X[i,:]' .* p1(X[i,:],β) .* (1 .- p1(X[i,:],β)),1:size(X)[1]))
        partial = -sum(map(i -> X[i,:] .* (y[i] .- p1(X[i,:],β)), 1:size(X)[1]))
        β = β - inv(partialsq) * partial
        newLoss = sum(-y.* (X * β) + log.(1 .+ exp.(X * β)))
        dLoss = abs(newLoss - Loss)
        Loss = newLoss
    end
    β
end

LogisticRegression (generic function with 1 method)

In [90]:
res = LogisticRegression([density sugarcontent],label)

3×1 Array{Float64,2}:
  3.158300358361756
 12.521114859178388
 -4.428831823031115

In [97]:
y =  1 ./ (1 .+ exp.(-[density sugarcontent ones(size(density))] * res)) 

17×1 Array{Float64,2}:
 0.9715906528851437  
 0.9384067868528045  
 0.7066367056452436  
 0.81353256136833    
 0.5048055697572374  
 0.4530059767140236  
 0.2603706024194883  
 0.39970382306470326 
 0.23397826238436087 
 0.4211078611154841  
 0.050147183643707266
 0.10852039530451799 
 0.40256752894281306 
 0.531297092936248   
 0.7926492157379162  
 0.11608144323446899 
 0.2956000317899552  

In [98]:
for yy ∈ y
    println(yy > 0.5 ? 1 : 0)
end

1
1
1
1
1
0
0
0
0
0
0
0
0
1
1
0
0
